package exam2;

import data.DbContext;
import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Year;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Car;
import models.Owner;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class AppInterface extends javax.swing.JFrame {

  /**
   * Creates new form AppInterface
   */

  private boolean ins_ok;
  private int ownerId = -1;
  DbContext db = new DbContext();
  
  private String filterByGenderValue;
  
  
  public AppInterface() {
    initComponents();

    System.out.println("Welcome");
    affichage(filterByGenderValue);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        bloc_proprietaire = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jfCNI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jfFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jfLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jfPhoneNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jfDoB = new com.toedter.calendar.JDateChooser();
        bloc_proprietaire1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jfMarque = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jfModel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jfYear = new com.toedter.calendar.JYearChooser();
        jLabel10 = new javax.swing.JLabel();
        jfMatricule = new javax.swing.JTextField();
        jfTransmission = new javax.swing.JComboBox<>();
        jfValidate = new javax.swing.JButton();
        jfCancel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jfTables = new javax.swing.JTable();
        jfFilterByGender = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAMA AUTO");

        bloc_proprietaire.setBorder(javax.swing.BorderFactory.createTitledBorder("Owner"));

        jLabel1.setText("CNI");

        jfCNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jfCNIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jfCNIFocusLost(evt);
            }
        });

        jLabel2.setText("First Name");

        jfFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfFirstNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Last Name");

        jLabel4.setText("Phone Number");

        jLabel5.setText("DoB");

        jfDoB.setToolTipText("");
        jfDoB.setDateFormatString("yyyy-MM-dd");
        jfDoB.setMinSelectableDate(new java.util.Date(-62135765899000L));

        javax.swing.GroupLayout bloc_proprietaireLayout = new javax.swing.GroupLayout(bloc_proprietaire);
        bloc_proprietaire.setLayout(bloc_proprietaireLayout);
        bloc_proprietaireLayout.setHorizontalGroup(
            bloc_proprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloc_proprietaireLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(bloc_proprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(46, 46, 46)
                .addGroup(bloc_proprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jfCNI)
                    .addComponent(jfFirstName)
                    .addComponent(jfLastName)
                    .addComponent(jfPhoneNumber)
                    .addComponent(jfDoB, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bloc_proprietaireLayout.setVerticalGroup(
            bloc_proprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloc_proprietaireLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bloc_proprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfCNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bloc_proprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bloc_proprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bloc_proprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bloc_proprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jfDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bloc_proprietaire1.setBorder(javax.swing.BorderFactory.createTitledBorder("Car"));

        jLabel6.setText("Marque");

        jLabel7.setText("Modele");

        jfModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfModelActionPerformed(evt);
            }
        });

        jLabel8.setText("Transmission");

        jLabel9.setText("Year");

        jLabel10.setText("Matricule");

        jfTransmission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automatique", "Manuel" }));
        jfTransmission.setToolTipText("");

        javax.swing.GroupLayout bloc_proprietaire1Layout = new javax.swing.GroupLayout(bloc_proprietaire1);
        bloc_proprietaire1.setLayout(bloc_proprietaire1Layout);
        bloc_proprietaire1Layout.setHorizontalGroup(
            bloc_proprietaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloc_proprietaire1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(bloc_proprietaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(bloc_proprietaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jfMarque, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(jfModel)
                    .addComponent(jfYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jfMatricule)
                    .addComponent(jfTransmission, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        bloc_proprietaire1Layout.setVerticalGroup(
            bloc_proprietaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bloc_proprietaire1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(bloc_proprietaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jfMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bloc_proprietaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfMarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bloc_proprietaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bloc_proprietaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jfTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bloc_proprietaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jfYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jfValidate.setText("Validate");
        jfValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfValidateActionPerformed(evt);
            }
        });

        jfCancel.setText("Cancel");
        jfCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfCancelActionPerformed(evt);
            }
        });

        jfTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CNI", "FIRST_NAME", "LAST_NAME", "PHONE", "BRAND", "YEAR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jfTables);

        jfFilterByGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Male", "Female" }));
        jfFilterByGender.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jfFilterByGenderItemStateChanged(evt);
            }
        });
        jfFilterByGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfFilterByGenderActionPerformed(evt);
            }
        });

        jLabel11.setText("Filter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jfCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jfValidate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bloc_proprietaire1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bloc_proprietaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jfFilterByGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(bloc_proprietaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bloc_proprietaire1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jfValidate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jfFilterByGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void jfFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfFirstNameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jfFirstNameActionPerformed

  private void jfModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfModelActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jfModelActionPerformed

  private void jfCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfCancelActionPerformed
    // TODO add your handling code here:
    System.out.println("Cancel..");
    cancel_btn();
  }//GEN-LAST:event_jfCancelActionPerformed

  private void jfValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfValidateActionPerformed
    // TODO add your handling code here:
    form_validator();
    // JOptionPane.showMessageDialog(this, "Good!! Inserted");
    // JOptionPane.showMessageDialog(this, row > 0 ? "insert" : "not insert");
  }//GEN-LAST:event_jfValidateActionPerformed

    private void jfCNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfCNIFocusLost
        
        // if cni exist set value on form
        if(!jfCNI.getText().isEmpty()){
            String __cni = jfCNI.getText();
            
            String tableName = "auto_owners";
            String[] keys = {"CNI"};
            String[] symbols = {"="};
            String[] values = {__cni};
            
            try {
                ResultSet result = db.queryPrepare(tableName, keys, symbols, values, 0);
                List row = new ArrayList();

                int columnCount = db.getColumnsFromTable(tableName).length;
                    
                while (result.next()) {
                    //row = new Vector(columnCount);
                    for (int i = 1; i <= columnCount; i++) {
                        row.add(result.getString(i));
                    }
                    break;
                }
                
                if (row.isEmpty()){
                    clear_all_without_cni();
                    return;
                }
                
                
                jfFirstName.setText((String) row.get(1));
                jfLastName.setText((String) row.get(2));
                jfPhoneNumber.setText((String) row.get(3));
                jfCNI.setText((String) row.get(4));
                
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                try {
                    Date date = dateFormat.parse(row.get(5).toString());
                    jfDoB.setDate(date);
                    
                    System.out.println(date);
                    System.out.println(row.get(5));
                } catch (Exception e) {
                    e.printStackTrace();
                }
                
                // (row.get(6));
                
                System.out.println("");
                
            } catch (SQLException ex) {
                Logger.getLogger(AppInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jfCNIFocusLost

    private void jfCNIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfCNIFocusGained
        if(jfCNI.getText().trim().isEmpty()){
            jfCNI.setText("");
        }else{
            jfCNI.getText();
        }
    }//GEN-LAST:event_jfCNIFocusGained

    private void jfFilterByGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfFilterByGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfFilterByGenderActionPerformed

    private void jfFilterByGenderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jfFilterByGenderItemStateChanged
        // TODO add your handling code here:
        filterByGenderValue = (String) jfFilterByGender.getSelectedItem();
        System.out.println("Selected value: " + filterByGenderValue);
        
        affichage(filterByGenderValue);
    }//GEN-LAST:event_jfFilterByGenderItemStateChanged



  private void form_validator() {
    try {
        // validation des champs
        if(input_validate() == false){
            JOptionPane.showMessageDialog(this, "/!\\ Tous les champs sont obligatoires");
            return;
        }
        
        // owner
        String _firstname = jfFirstName.getText();
        String _lastname = jfLastName.getText();
        String _phone = jfPhoneNumber.getText();
        String _cni = jfCNI.getText();
        Date _dob = jfDoB.getDate();
        
      
        // car
        String _matricule = jfMatricule.getText();
        String _marque = jfMarque.getText();
        String _model = jfModel.getText();
        String _transmission = jfTransmission.getSelectedIndex() == 0 ? "Automatique" : "Manuel";
        int _year = jfYear.getValue(); // set current year

        try {
            // Formatage de la date en chaîne
            DateFormat outputDateFormat = new SimpleDateFormat("yy-MM-dd");
            String dateStr = outputDateFormat.format(_dob);

            String[] parts = dateStr.split("-");
            int o_year = Integer.parseInt(parts[0]);
            int o_month = Integer.parseInt(parts[1]);
            int o_day = Integer.parseInt(parts[2]);

            Date dob = new Date(o_year, o_month, o_day);
            System.out.println(dob);
            Owner own = new Owner();
            own.setFirstName(_firstname);
            own.setLastName(_lastname);
            own.setPhone(_phone);
            own.setCni(_cni);
            own.setDob(dob);

            String[] cols = db.getColumnsFromTable("auto_owners");
            Object[] owner_vals = owner_values_object(own);

            ownerId = db.insertIntoTable("auto_owners", cols, owner_vals, 1);

            affichage(filterByGenderValue);
        } catch (SQLException err) {
            System.out.println(err.getMessage());
            err.getStackTrace();
        }

        //
        if (ownerId == -1) return;

        try {
            System.out.println("");
            // String matricule, String marque, String model, int transmission, int annee, int ownerId
            Car car = new Car(_matricule,_marque, _model, _transmission, _year, ownerId);
            
            System.out.println(car);
            String[] cols = db.getColumnsFromTable("auto_cars");
            Object[] car_vals = car_values_object(car);

            db.insertIntoTable("auto_cars", cols, car_vals, 1);
          
            affichage(filterByGenderValue);
          
        } catch (SQLException err) {
            System.out.println(err.getMessage());
            err.getStackTrace();
        }
        
        // Altert and clear form
        JOptionPane.showMessageDialog(this, "Data inserted");
        cancel_btn();
      
    } catch (Exception ex) {
        System.out.println("Les champs sont obligatoires");
        JOptionPane.showMessageDialog(this, "/!\\ Tous les champs sont obligatoires");
    }
    
  }
  
  public boolean input_validate(){
    // owner
    String _cni = jfCNI.getText();
    String _firstname = jfFirstName.getText();
    String _lastname = jfLastName.getText();
    String _phone = jfPhoneNumber.getText();
    
    Date _dob = jfDoB.getDate();

    // car
    String _matricule = jfMatricule.getText();
    String _marque = jfMarque.getText();
    String _model = jfModel.getText();
    String _transmission = jfTransmission.getSelectedIndex() == 0 ? "Automatique" : "Manuel";
    
    return !_transmission.trim().isEmpty() && _dob != null && !_cni.trim().isEmpty() && !_firstname.trim().isEmpty() && !_lastname.trim().isEmpty() && !_phone.trim().isEmpty() && !_matricule.trim().isEmpty() && !_marque.trim().isEmpty() && !_model.trim().isEmpty();
  }

  private Object[] car_values_object(Car car) {
    List<Object> carList = new ArrayList<>();

    carList.add(car.getMatricule());

    carList.add(car.getModel());
    carList.add(car.getMarque());
    carList.add(car.getTransmission());
    carList.add(car.getAnnee());
    carList.add(car.getOwnerId());

    Object[] cars = carList.toArray();

    return cars;
  }

  private Object[] owner_values_object(Owner own) {
    List<Object> carList = new ArrayList<>();

    carList.add(own.getFirstName());
    carList.add(own.getLastName());
    carList.add(own.getPhone());
    carList.add(own.getCni());
    carList.add(own.getDob());

    Object[] owners = carList.toArray();

    return owners;
  }
  
private void cancel_btn() {
    jfCNI.setText("");
    jfFirstName.setText("");
    jfLastName.setText("");
    jfPhoneNumber.setText("");
    jfMatricule.setText("");
    jfDoB.setDate(null);
    

    jfMarque.setText("");
    jfModel.setText("");
    jfTransmission.setSelectedIndex(0);
    jfYear.setValue(Year.now().getValue()); // set current year

}

  private void clear_all_without_cni() {
    jfFirstName.setText("");
    jfLastName.setText("");
    jfPhoneNumber.setText("");
    jfMatricule.setText("");
    jfDoB.setDate(null);
    

    jfMarque.setText("");
    jfModel.setText("");
    jfTransmission.setSelectedIndex(0);
    jfYear.setValue(Year.now().getValue()); // set current year

  }

private void affichage(String filter) {
    String sql;
    
    if("Female".equals(filter)){
        sql = "SELECT CNI,FIRST_NAME,LAST_NAME,PHONE,MARQUE,ANNEE FROM auto_owners, auto_cars WHERE auto_owners.OWNER_ID=auto_cars.OWNER_ID AND auto_owners.cni like '2%'";  
    }else if("Male".equals(filter)){
        sql = "SELECT CNI,FIRST_NAME,LAST_NAME,PHONE,MARQUE,ANNEE FROM auto_owners, auto_cars WHERE auto_owners.OWNER_ID=auto_cars.OWNER_ID AND auto_owners.cni like '1%'";  
    }else{
        sql = "SELECT CNI,FIRST_NAME,LAST_NAME,PHONE,MARQUE,ANNEE FROM auto_owners, auto_cars WHERE auto_owners.OWNER_ID=auto_cars.OWNER_ID";
    }
      
    try {
      ResultSet rs = db.query(sql);
      db.displayTable(rs, jfTables);
    } catch (Exception ex) {
      Logger
        .getLogger(AppInterface.class.getName())
        .log(Level.SEVERE, null, ex);
    }
}

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java
        .util.logging.Logger.getLogger(AppInterface.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java
        .util.logging.Logger.getLogger(AppInterface.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java
        .util.logging.Logger.getLogger(AppInterface.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java
        .util.logging.Logger.getLogger(AppInterface.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {

        public void run() {
          new AppInterface().setVisible(true);
        }
      }
    );
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bloc_proprietaire;
    private javax.swing.JPanel bloc_proprietaire1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jfCNI;
    private javax.swing.JButton jfCancel;
    private com.toedter.calendar.JDateChooser jfDoB;
    private javax.swing.JComboBox<String> jfFilterByGender;
    private javax.swing.JTextField jfFirstName;
    private javax.swing.JTextField jfLastName;
    private javax.swing.JTextField jfMarque;
    private javax.swing.JTextField jfMatricule;
    private javax.swing.JTextField jfModel;
    private javax.swing.JTextField jfPhoneNumber;
    private javax.swing.JTable jfTables;
    private javax.swing.JComboBox<String> jfTransmission;
    private javax.swing.JButton jfValidate;
    private com.toedter.calendar.JYearChooser jfYear;
    // End of variables declaration//GEN-END:variables
}
