/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exam2;

import data.DbContext;
import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.time.Year;
import java.util.Date;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Car;
import models.Owner;

/**
 *
 * @author user
 */
public class AppInterface extends javax.swing.JFrame {

  /**
   * Creates new form AppInterface
   */
  public AppInterface() {
    initComponents();

    System.out.println("Welcome");
  }

  DbContext db = new DbContext();

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bloc_proprietaire = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jfCNI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jfFirstName = new javax.swing.JTextField();
        jfGenderMale = new javax.swing.JRadioButton();
        jfGenderFemale = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jfLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jfPhoneNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jfDoB = new com.toedter.calendar.JDateChooser();
        bloc_proprietaire1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jfMarque = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jfModel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jfTransmission = new javax.swing.JSpinner();
        jfYear = new com.toedter.calendar.JYearChooser();
        jLabel10 = new javax.swing.JLabel();
        jfMatricule = new javax.swing.JTextField();
        jfValidate = new javax.swing.JButton();
        jfCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAMA AUTO");

        bloc_proprietaire.setBorder(javax.swing.BorderFactory.createTitledBorder("Owner"));

        jLabel1.setText("CNI");

        jfCNI.setText("0185-7852-589");

        jLabel2.setText("First Name");

        jfFirstName.setText("John");
        jfFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfFirstNameActionPerformed(evt);
            }
        });

        buttonGroup1.add(jfGenderMale);
        jfGenderMale.setSelected(true);
        jfGenderMale.setText("Male");
        jfGenderMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfGenderMaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(jfGenderFemale);
        jfGenderFemale.setText("Female");
        jfGenderFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfGenderFemaleActionPerformed(evt);
            }
        });

        jLabel3.setText("Last Name");

        jfLastName.setText("Doe");

        jLabel4.setText("Phone Number");

        jfPhoneNumber.setText("221778885522");

        jLabel5.setText("DoB");

        jfDoB.setToolTipText("");
        jfDoB.setDateFormatString("yyyy-MM-dd");
        jfDoB.setMinSelectableDate(new java.util.Date(-62135765899000L));

        javax.swing.GroupLayout bloc_proprietaireLayout = new javax.swing.GroupLayout(bloc_proprietaire);
        bloc_proprietaire.setLayout(bloc_proprietaireLayout);
        bloc_proprietaireLayout.setHorizontalGroup(
            bloc_proprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloc_proprietaireLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(bloc_proprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(46, 46, 46)
                .addGroup(bloc_proprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bloc_proprietaireLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jfGenderMale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jfGenderFemale))
                    .addComponent(jfCNI)
                    .addComponent(jfFirstName)
                    .addComponent(jfLastName)
                    .addComponent(jfPhoneNumber)
                    .addComponent(jfDoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bloc_proprietaireLayout.setVerticalGroup(
            bloc_proprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloc_proprietaireLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bloc_proprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfGenderMale)
                    .addComponent(jfGenderFemale, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bloc_proprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfCNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bloc_proprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bloc_proprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bloc_proprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bloc_proprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jfDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        bloc_proprietaire1.setBorder(javax.swing.BorderFactory.createTitledBorder("Car"));

        jLabel6.setText("Marque");

        jfMarque.setText("0185-7852-589");

        jLabel7.setText("Modele");

        jfModel.setText("John");
        jfModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfModelActionPerformed(evt);
            }
        });

        jLabel8.setText("Transmission");

        jLabel9.setText("Year");

        jLabel10.setText("Matricule");

        jfMatricule.setText("AAAA-0001-AA");

        javax.swing.GroupLayout bloc_proprietaire1Layout = new javax.swing.GroupLayout(bloc_proprietaire1);
        bloc_proprietaire1.setLayout(bloc_proprietaire1Layout);
        bloc_proprietaire1Layout.setHorizontalGroup(
            bloc_proprietaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloc_proprietaire1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(bloc_proprietaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(bloc_proprietaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jfMarque, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(jfModel)
                    .addComponent(jfTransmission)
                    .addComponent(jfYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jfMatricule))
                .addGap(16, 16, 16))
        );
        bloc_proprietaire1Layout.setVerticalGroup(
            bloc_proprietaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bloc_proprietaire1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bloc_proprietaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jfMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bloc_proprietaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfMarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bloc_proprietaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bloc_proprietaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jfTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bloc_proprietaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jfYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jfValidate.setText("Validate");
        jfValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfValidateActionPerformed(evt);
            }
        });

        jfCancel.setText("Cancel");
        jfCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jfCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jfValidate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bloc_proprietaire, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bloc_proprietaire1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(bloc_proprietaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bloc_proprietaire1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfValidate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void jfGenderFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfGenderFemaleActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jfGenderFemaleActionPerformed

  private void jfGenderMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfGenderMaleActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jfGenderMaleActionPerformed

  private void jfFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfFirstNameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jfFirstNameActionPerformed

  private void jfModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfModelActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jfModelActionPerformed

  private void jfCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfCancelActionPerformed
    // TODO add your handling code here:
    System.out.println("Cancel..");
    cancel_btn();
  }//GEN-LAST:event_jfCancelActionPerformed

  private void jfValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfValidateActionPerformed
    // TODO add your handling code here:
    form_validator();
  }//GEN-LAST:event_jfValidateActionPerformed

  private void cancel_btn() {
    jfCNI.setText("");
    jfFirstName.setText("");
    jfLastName.setText("");
    jfPhoneNumber.setText("");
    jfDoB.setDate(null);

    jfMarque.setText("");
    jfModel.setText("");
    jfTransmission.setValue(0);
    jfYear.setValue(Year.now().getValue()); // set current year

    // default gender Male
    jfGenderMale.setSelected(true);
  }

  private void form_validator() {
     
    //ArrayList<<Owner,Car>> queries = new ArrayList<<Owner,Car>>();
      
    try{
        // owner
        String _cni = jfCNI.getText();
        String _firstname = jfFirstName.getText();
        String _lastname = jfLastName.getText();
        String _phone = jfPhoneNumber.getText();
        Date _dob = jfDoB.getDate();
        String _formatDob = new SimpleDateFormat("yyyy-MM-dd").format(_dob);

        // car
        String _matricule = jfMatricule.getText();
        String _marque = jfMarque.getText();
        String _model = jfModel.getText();
        int _transmission = (int) jfTransmission.getValue();
        int _year = jfYear.getValue(); // set current year

        // default gender Male
        int _gender = jfGenderMale.isSelected() ? 1 : 0;
        
        if(!_cni.trim().isEmpty() && !_firstname.trim().isEmpty() 
            && !_lastname.trim().isEmpty() && !_phone.trim().isEmpty() 
            && !_formatDob.trim().isEmpty() && !_matricule.trim().isEmpty()
            && !_marque.trim().isEmpty() && !_model.trim().isEmpty()){
            
            // String firstName, String lastName, String phone, String cni, Date dob
            Owner ow = new Owner(_firstname, _lastname, _phone, _cni, _dob, _gender );
            // String matricule, String marque, String model, int transmission, int annee
            Car car = new Car(_matricule, _marque, _model, _transmission, _year );
            
            System.out.println(ow);
            System.out.println(car);
        }
        //return null;
    }catch(Exception ex){
        System.out.println("Les champs sont obligatoires");
    }
    //return null;
  }
  
  
  
  private void insert(boolean returnId) {
   
    // INSERT INTO auto_owners VALUES("Maurice", "LEMAIRE", "221778885522", "0125-147-258", "1990-02-19")
    String sql = "INSERT INTO auto_owners VALUES(?,?,?,?,?,?)";
    
    /*PreparedStatement pstmt = db.insert(sql);
    try {
        pstmt.setString(1, "Fatou");
        pstmt.setString(2, "FALL");
        pstmt.setString(3, "221760001122");
        pstmt.setString(4, "0155-563-147");
        pstmt.setString(5, "2023-01-19");
        pstmt.setString(6, "1");

        pstmt.executeUpdate();
        System.out.println("Insertion réussie !");
    } catch (SQLException ex) {
        Logger.getLogger(AppInterface.class.getName()).log(Level.SEVERE, null, ex);
    }*/

    

    
    // ResultSet rs = db.query("SELECT * FROM auto_owners");
    
    /*try {
        while(rs.next()){
            try {
                System.out.println(rs.getString(1));
            } catch (SQLException ex) {
                Logger.getLogger(AppInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(AppInterface.class.getName()).log(Level.SEVERE, null, ex);
    }*/
    
  }

  
  
  
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java
        .util.logging.Logger.getLogger(AppInterface.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java
        .util.logging.Logger.getLogger(AppInterface.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java
        .util.logging.Logger.getLogger(AppInterface.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java
        .util.logging.Logger.getLogger(AppInterface.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {

        public void run() {
          new AppInterface().setVisible(true);
        }
      }
    );
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bloc_proprietaire;
    private javax.swing.JPanel bloc_proprietaire1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jfCNI;
    private javax.swing.JButton jfCancel;
    private com.toedter.calendar.JDateChooser jfDoB;
    private javax.swing.JTextField jfFirstName;
    private javax.swing.JRadioButton jfGenderFemale;
    private javax.swing.JRadioButton jfGenderMale;
    private javax.swing.JTextField jfLastName;
    private javax.swing.JTextField jfMarque;
    private javax.swing.JTextField jfMatricule;
    private javax.swing.JTextField jfModel;
    private javax.swing.JTextField jfPhoneNumber;
    private javax.swing.JSpinner jfTransmission;
    private javax.swing.JButton jfValidate;
    private com.toedter.calendar.JYearChooser jfYear;
    // End of variables declaration//GEN-END:variables
}
